### ISSUE TITLE
Long_FFTs_for_CMSIS_DSP

### ISSUE THREAD

**Issue by SharathAV** [Treeed/Long_FFTs_for_CMSIS_DSP#1]
Hello,
The CMSIS DSP library supports a 4096-point FFT, but my project requires a 16384-point FFT. "I successfully added the extra library files from 'https://github.com/Treeed/Long_FFTs_for_CMSIS_DSP/tree/master' and performed a 16384-point FFT, obtaining the output. However, the FFT takes too much time, with a delay of around 27 to 30 seconds. Why is this taking so long, and what can be done to reduce the time and improve efficiency?"

**Comment by Treeed** [comment]
Hi,
I just tested a 16384 point FFT with the compiler set to optimization for speed (-Ofast) and it seems to take about 9ms on average for me. Calculating the complex magnitude takes another ~2ms. Without optimization (-O0) it takes ~47ms for the FFT and ~9ms for the Magnitude. The actual times should probably be a bit less since I tested this within a project that already has some interrupts and DMA operations going on. 
The highest I could get it to was ~200ms by turning off the floating point unit and optimization entirely.

I'm using GNU Tools for STM32 (10.3-2021.10) which contains some GCC 10.3 on an STM32F479NG running at 180MHz.

My code looks something like this:
Init stuffs:
```cpp
#define FFT_LEN (16384)

arm_rfft_fast_instance_f32_extra fft_tables_main;
float32_t sample_memory[FFT_LEN];
uint16_t sample_memory_cursor;
float32_t fft_buffer1[FFT_LEN];
float32_t fft_buffer2[FFT_LEN];

arm_rfft_fast_init_f32_extra(&fft_tables_main, FFT_LEN);
```

FFT calculation:
```cpp
  for(int i = 0; i < FFT_LEN; i++){
    fft_buffer1[i] = sample_memory[(sample_memory_cursor+i)%FFT_LEN]*hamming[i];
  }
  unsigned long start = HAL_GetTick();
  arm_rfft_fast_f32_extra(&fft_tables_main, fft_buffer1, fft_buffer2, false);
  arm_cmplx_mag_f32(fft_buffer2, fft_buffer1, FFT_LEN);
  volatile unsigned long diff = HAL_GetTick()-start;
```


What device are you using? Could you show a minimum working example that exhibits your problem?

**Comment by SharathAV** [comment]
Hi,
    Thank you for your reply. I'm facing the FFT delayed response issue.
Any help would be Appreciated.
I'm also using GNU Tools for STM32 which contains some GCC on an
STM32H745ZIT6 running at 400MHz.(STM32CubeIDE  -workspace1.13.1)

Bellow Provided  code looks like this:
#define  FFT_SIZE                                   16384
#define  fft_Size                                       16384

// Declare and initialize the FFT instance structure
arm_status fft_status;
arm_rfft_fast_instance_f32_extra fft_instance;

float_t fft_input_buffer[fft_Size ];  // Define buffer and FFT size
float_t fft_output_buffer[fft_Size];
uint16_t  index_1 = 0;
float_t FFT[FFT_SIZE];
float_t FFT_VALUE = 0;
float_t FFT_INPUT = 0;

// Initialize caches for faster performance   ****(if i enable the I&D
cache for 16384 points FFT takes 7 seconds  otherwise it will take 7*4times
= 28 seconds)
SCB_EnableICache();
SCB_EnableDCache();

 fft_status = arm_rfft_fast_init_f32_extra(&fft_instance, FFT_SIZE);
  if (fft_status != ARM_MATH_SUCCESS)
   {
  // FFT initialization failed, handle the error
    while (1)
   {
      // Error handling...
   }
   }

// FFT processing                            //collecting samples from ADC
and passing to it
void Process_FFT(float * pfftin_array)
{
unsigned short fl_i;
for(fl_i = 0; fl_i<FFT_SIZE; fl_i++)
{
fft_input_buffer[fl_i] = 0.0001007080078125 * pfftin_array[fl_i];
}
   // Perform the FFT
arm_rfft_fast_f32_extra(&fft_instance, fft_input_buffer, fft_output_buffer,
0);

   // Visualize the results (you can customize this part as needed)
   for (uint32_t i = 0; i < FFT_SIZE / 2; i++)
   {
   float_t real = fft_output_buffer[i * 2];
   float_t imag = fft_output_buffer[i * 2 + 1];
   float_t magnitude = sqrtf(real * real + imag * imag);
FFT[index_1] = magnitude;
index_1++;

if(index_1>=FFT_SIZE)
{
index_1=0;
}
for(int m=0; m<=FFT_SIZE; m++)
{
FFT_VALUE=FFT[m];
FFT_INPUT = FFT_VALUE*10;
}
    }
}

**Comment by Treeed** [comment]
Hi,
I was able to reproduce your results with optimizations turned off. It turns out the slow part in your code is not the FFT. 
You have a second for loop inside your outer for loop, so effectively you iterate FFT_SIZE/2*FFT_SIZE times which takes a long time. 
I have commented your code in the following to point out a few things

```cpp
void Process_FFT(float * pfftin_array)
{
  unsigned short fl_i;
  for(fl_i = 0; fl_i<FFT_SIZE; fl_i++)
  {
    fft_input_buffer[fl_i] = 0.0001007080078125 * pfftin_array[fl_i];
  }
  // Perform the FFT
  arm_rfft_fast_f32_extra(&fft_instance, fft_input_buffer, fft_output_buffer,
                          0);

  //iterates FFT_SIZE/2 times
  for (uint32_t i = 0; i < FFT_SIZE / 2; i++)
  {
    // This bit looks fine in general, but I would suggest you use 
    // arm_cmplx_mag_f32(fft_buffer1, fft_buffer2, FFT_LEN); if you are concerned about speed. 
    // It is part of the normal arm CMSIS DSP library
    float_t real = fft_output_buffer[i * 2];
    float_t imag = fft_output_buffer[i * 2 + 1];
    float_t magnitude = sqrtf(real * real + imag * imag);

    // Do you want to store two consecutive FFTs in your buffer? This bit looks a bit weird. 
    // If you only want one FFT, make the buffer FFT_SIZE/2 long and just use i for the index
    FFT[index_1] = magnitude; 
    index_1++;

    if(index_1>=FFT_SIZE)
    {
      index_1=0;
    }

    // This bit is still inside the outer loop, so it gets executed every time you 
    // calculate a single value of your magnitude. This is why your loop takes so long.
    // Also, it reads uninitialized memory, since it iterates up to FFT_SIZE,
    // but the maximum position in FFT is at FFT_SIZE-1
    // And even then, it's not clear what it should do. FFT_INPUT and FFT_VALUE are scalar 
    // values which get overwritten with every iteration of the loop
    for(int m=0; m<=FFT_SIZE; m++)
    {
      FFT_VALUE=FFT[m];
      FFT_INPUT = FFT_VALUE*10;
    }
  }
}
```

I would suggest you set up a debugger to evaluate your code. During debugging you can easily see what which line does and in what order the lines are executed. Also, for something this slow it even allows you to figure out which part takes long by just setting some breakpoints and seeing how long it takes to jump from one to the next.
STM32CubeIDE comes setup with a debugger and works quite well.
A debug adapter is part of all STM32 Discovery and Nucleo boards, you probably have one since you are able to program your board.
To look at more subtle timing differences you can place two or more lines like so
```cpp
  unsigned long start = HAL_GetTick();
  // the code you want to time goes here
  volatile unsigned long diff = HAL_GetTick()-start;
  asm("nop"); //place a breakpoint in this line and read the value of diff with a debugger
  // The value will be the elapsed time in milliseconds
```
this is how I got the timing values I reported above.

If you care about even finer timing you can toggle a pin and look at it with a logic analyzer or oscilloscope. You can get a cheap knockoff usb logic analyzer from China for a few bucks.

**Comment by SharathAV** [comment]
Hi,
Thank you for your response,By observing the code you concluded problem is
not in  FFT after going to calculate  real,imag and magnitude this part
taking too much of time so your suggestion is to use this function   //
arm_cmplx_mag_f32(fft_buffer1, fft_buffer2, FFT_LEN); instead of using the
bellow function right ?
// Visualize the results (you can customize this part as needed)
   for (uint32_t i = 0; i < FFT_SIZE / 2; i++)
   {
            float_t real = fft_output_buffer[i * 2];
            float_t imag = fft_output_buffer[i * 2 + 1];
            float_t magnitude = sqrtf(real * real + imag * imag);
             FFT[index_1] = magnitude;
             index_1++;

             if(index_1>=FFT_SIZE)
             {
                      index_1=0;
              }
              for(int m=0; m<=FFT_SIZE; m++)
             {
                      FFT_VALUE=FFT[m];
                      FFT_INPUT = FFT_VALUE*10;
              }
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
I Created one Array
float ADC_TEMP_Ch11[16384]={0, 0.000383495187571396, 0.000766990318742704,
0.00115048533711385, 0.00153398018628477, ...........etc
  while (1)        //Stop running other function and run only this function
and check the timing in Osciloscope by that obtaining the delay bellow
  {
         HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
           Process_FFT(ADC_TEMP_Ch11);
}
  samples(For 1Ch)            delay(when i enable I&D cache)
delay(When not enable I&D cache)
   1024                                      25ms
                    100ms (4 times Increased)
   2048                                      100ms
                   400ms
   4096                                      400ms
                    1.7seconds
   8192                                       1.7s
                        7s
   16384                                      7s
                         28s
(In my project i have a 4 channels)

**Comment by Treeed** [comment]
Hi,

my main point is that you need to remove this part from your code:

```cpp
              for(int m=0; m<=FFT_SIZE; m++)
             {
                      FFT_VALUE=FFT[m];
                      FFT_INPUT = FFT_VALUE*10;
              }
```
Without this part the whole function only takes a couple milliseconds in my tests. 

All the other comments were just suggestions to gain a few more percent, but not too critical.
